"""empty message

Revision ID: 4d68ea973187
Revises: 8c9a66dbc1f3
Create Date: 2024-10-01 23:14:00.775192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d68ea973187'
down_revision = '8c9a66dbc1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.String(length=255), server_default='', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
