"""empty message

Revision ID: 9d49e494a91c
Revises: e90b6c826262
Create Date: 2024-10-01 23:44:39.276257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d49e494a91c'
down_revision = 'e90b6c826262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_shelter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_shelter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('flood', sa.INTEGER(), nullable=False),
    sa.Column('landslide', sa.INTEGER(), nullable=False),
    sa.Column('hightide', sa.INTEGER(), nullable=False),
    sa.Column('earthquake', sa.INTEGER(), nullable=False),
    sa.Column('tsunami', sa.INTEGER(), nullable=False),
    sa.Column('fire', sa.INTEGER(), nullable=False),
    sa.Column('inland_flooding', sa.INTEGER(), nullable=False),
    sa.Column('volcano', sa.INTEGER(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('altitude', sa.FLOAT(), nullable=True),
    sa.Column('capacity', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
