"""empty message

Revision ID: b46fa6e056d3
Revises: b3772cff87bf
Create Date: 2024-10-05 06:31:40.098768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46fa6e056d3'
down_revision = 'b3772cff87bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('stockname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('note',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('expiration',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('condition',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('condition',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('expiration',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('note',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('stockname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
