"""empty message

Revision ID: e90b6c826262
Revises: fc4500923bee
Create Date: 2024-10-01 23:26:41.629878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90b6c826262'
down_revision = 'fc4500923bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.alter_column('flood',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('landslide',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hightide',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('earthquake',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tsunami',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fire',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('inland_flooding',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('volcano',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.alter_column('volcano',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('inland_flooding',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fire',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tsunami',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('earthquake',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hightide',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('landslide',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('flood',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
