"""empty message

Revision ID: fc4500923bee
Revises: 4d68ea973187
Create Date: 2024-10-01 23:24:23.573535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4500923bee'
down_revision = '4d68ea973187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.alter_column('altitude',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.alter_column('altitude',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
