"""empty message

Revision ID: 98a991ce980f
Revises: 
Create Date: 2024-09-24 13:22:48.897292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a991ce980f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('flood', sa.Integer(), nullable=True),
    sa.Column('landslide', sa.Integer(), nullable=True),
    sa.Column('hightide', sa.Integer(), nullable=True),
    sa.Column('earthquake', sa.Integer(), nullable=True),
    sa.Column('tsunami', sa.Integer(), nullable=True),
    sa.Column('fire', sa.Integer(), nullable=True),
    sa.Column('inland_flooding', sa.Integer(), nullable=True),
    sa.Column('volcano', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelter')
    # ### end Alembic commands ###
